#!/usr/bin/env python3
"""Generate Ghostty theme files from palettes.py.

Usage: python3 make_ghostty.py  (writes ghostty/themes/<name>)

Ghostty themes are plain config fragments: the same key = value syntax as
ghostty/config, limited to color keys. `theme = <name>` in the main config
picks one up from ~/.config/ghostty/themes/.
"""
import sys
from pathlib import Path

here = Path(__file__).resolve().parent
sys.path.insert(0, str(here.parent))
from palettes import PALETTES  # noqa: E402

# iTerm2 color name -> Ghostty key. "Bold" and "Link" have no Ghostty
# equivalent (it derives bold from the palette and does not color OSC 8
# links separately), so they are dropped.
KEYS = {
    "Background": "background",
    "Foreground": "foreground",
    "Cursor": "cursor-color",
    "Cursor Text": "cursor-text",
    "Selection": "selection-background",
    "Selected Text": "selection-foreground",
}

themes = here / "themes"
themes.mkdir(exist_ok=True)

for name, colors in PALETTES.items():
    lines = [
        f"# {name} — generated by ghostty/make_ghostty.py, do not edit by hand.",
        "# Palette lives in palettes.py; rerun the generator after changing it.",
        "",
    ]
    lines += [f"palette = {i}=#{colors[f'Ansi {i}']}" for i in range(16)]
    lines.append("")
    lines += [f"{key} = #{colors[src]}" for src, key in KEYS.items()]
    (themes / name).write_text("\n".join(lines) + "\n")
    print(f"wrote themes/{name}")
