# Gruvbox (dark) prompt colors. Sourced after p10k.zsh; overrides its colors.
# Palette: https://github.com/morhetz/gruvbox
# Pairs best with an iTerm2 background of #282828.

typeset -g POWERLEVEL9K_BACKGROUND='#3c3836'
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%F{#7c6f64}'
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='%F{#7c6f64}'

typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='#ebdbb2'
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#83a598'

typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#b8bb26'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#b8bb26'
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#fabd2f'
typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_COLOR='#b8bb26'
typeset -g POWERLEVEL9K_VCS_LOADING_VISUAL_IDENTIFIER_COLOR='#928374'

# Colors inside the git segment text (consumed by my_git_formatter)
typeset -g P10K_GIT_META_COLOR='#a89984'
typeset -g P10K_GIT_CLEAN_COLOR='#b8bb26'
typeset -g P10K_GIT_MODIFIED_COLOR='#fabd2f'
typeset -g P10K_GIT_UNTRACKED_COLOR='#83a598'
typeset -g P10K_GIT_CONFLICTED_COLOR='#fb4934'

typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND='#8ec07c'
typeset -g POWERLEVEL9K_STATUS_{OK,OK_PIPE}_FOREGROUND='#b8bb26'
typeset -g POWERLEVEL9K_STATUS_{ERROR,ERROR_SIGNAL,ERROR_PIPE}_FOREGROUND='#fb4934'
typeset -g POWERLEVEL9K_TIME_FOREGROUND='#928374'

typeset -g ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#7c6f64'
