# headroom — generated by tmux/make_tmux.py from palettes.py. Do not edit;
# change the palette and rerun the generator.

set -g status-style "bg=#1c1c28,fg=#a8a8c0"
set -g status-left "#[bg=#28283a,fg=#7c84f6,bold] #S #[default] "
set -g status-left-length 30
set -g status-right "#[fg=#7c84f6]#{?client_prefix,PREFIX ,}#[fg=#a8a8c0]#h "

setw -g window-status-format " #I #W "
setw -g window-status-current-format "#[bg=#28283a,fg=#7c84f6] #I #W "
setw -g window-status-bell-style "fg=#e8718a"
setw -g window-status-activity-style "fg=#7c84f6"

set -g pane-border-style "fg=#3a3a52"
set -g pane-active-border-style "fg=#7c84f6"
set -g display-panes-colour "#3a3a52"
set -g display-panes-active-colour "#7c84f6"

set -g message-style "bg=#28283a,fg=#eeeef6"
set -g mode-style "bg=#28283a,fg=#eeeef6"
