#!/usr/bin/env python3
"""Generate the tmux color theme from palettes.py.

Usage: python3 tmux/make_tmux.py   (writes tmux/headroom.tmux)

tmux.conf sources the output, so the status bar, borders and messages come
from the same palette as the prompt and the terminal profiles.
"""
import sys
from pathlib import Path

here = Path(__file__).resolve().parent
sys.path.insert(0, str(here.parent))
from palettes import PALETTES  # noqa: E402

P = PALETTES["headroom-dark"]
# Roles, mapped onto palette entries so nothing is invented here.
BAR = "#" + P["Ansi 0"]          # status bar surface, one step off the bg
SURFACE = "#" + P["Selection"]   # lifted block: session name, current window
BORDER = "#" + P["Ansi 8"]       # inactive pane borders
TEXT = "#" + P["Ansi 7"]         # regular status text
BRIGHT = "#" + P["Ansi 15"]      # messages and copy-mode selection
ACCENT = "#" + P["Ansi 12"]      # the one accent: active pane and window
ALERT = "#" + P["Ansi 1"]        # bell / activity

theme = f"""\
# headroom — generated by tmux/make_tmux.py from palettes.py. Do not edit;
# change the palette and rerun the generator.

set -g status-style "bg={BAR},fg={TEXT}"
set -g status-left "#[bg={SURFACE},fg={ACCENT},bold] #S #[default] "
set -g status-left-length 30
set -g status-right "#[fg={ACCENT}]#{{?client_prefix,PREFIX ,}}#[fg={TEXT}]#h "

setw -g window-status-format " #I #W "
setw -g window-status-current-format "#[bg={SURFACE},fg={ACCENT}] #I #W "
setw -g window-status-bell-style "fg={ALERT}"
setw -g window-status-activity-style "fg={ACCENT}"

set -g pane-border-style "fg={BORDER}"
set -g pane-active-border-style "fg={ACCENT}"
set -g display-panes-colour "{BORDER}"
set -g display-panes-active-colour "{ACCENT}"

set -g message-style "bg={SURFACE},fg={BRIGHT}"
set -g mode-style "bg={SURFACE},fg={BRIGHT}"
"""
out = here / "headroom.tmux"
out.write_text(theme)
print(f"wrote {out.relative_to(here.parent)}")
